### ISSUE TITLE
None of the links work

### ISSUE THREAD

**Issue by ChrisThompsonTLDR** [owen-it/laravel-auditing-doc#52]
https://github.com/owen-it/laravel-auditing-doc/blob/master/documentation.md

All the links go to 404

**Comment by quetzyg** [comment]
Yeah, not on GitHub anyway, those are supposed to be used in the actual site (http://www.laravel-auditing.com), since the version is replaced by the `{{ version }}` placeholder.

@anteriovieira, if we remove that, won't it work on the site anyway?

We could probably just get rid of the placeholder.

**Comment by quetzyg** [comment]
We'll keep it as is. Just access the documentation through the site.

**Comment by anteriovieira** [comment]
Hi guys

I commented with Quetzy that it was not worth the effort to adjust it but it made me a little restless. So I made some adjustments and now you can use one of the urls below to have access to the documentation.

- https://owen-it.gitbooks.io/laravel-auditing
- https://doc.laravel-auditing.com
- http://laravel-auditing.com
- https://github.com/owen-it/laravel-auditing-doc/blob/master/documentation.md
