### ISSUE TITLE
Tradução para o Audit presentation

### ISSUE THREAD

**Issue by sotnaspina** [owen-it/laravel-auditing-doc#57]
Olá,

Gostaria de compartilhar uma implementação que fiz para facilitar a tradução dos atributos/mensagens da auditoria.

Segue o link: [Gist: Laravel Auditing - Presentation Translation](https://gist.github.com/sotnaspina/14712548d90c889af796a47e28a589b5)

Desculpe se postei no lugar errado, não sabia onde mais postar.
Abraço!

**Comment by anteriovieira** [comment]
Olá @sotnaspina , tudo bem. Muito obrigado por sua contribuição.
Desculpe a demora em responde-lo, eu estive ausente esses ultimos dias.

@quetzyg pode dar uma olhada nisso por gentileza.

**Comment by quetzyg** [comment]
@anteriovieira, tal como já haviamos falado há umas semanas, a documentação é melhor ficar só pelo inglês, pois assim dá menos trabalho quando são feitas alterações ao pacote.

@sotnaspina , agradeço a contribuição, mas a verdade é que tu estás a traduzir apenas texto num exemplo, e semo o resto da documentação traduzida, o contributo perde qualquer sentido.

Esses exemplos que temos, não passam disso mesmo. Ou seja, não são a forma padrão/recomendada por nós, é apenas uma sugestão e quem quer usa como está ou adapta consoante as necessidades (tal como tu o fizeste).

Portanto, isto fica sem efeito.

Bem haja, de qualquer dos modos.
