### ISSUE TITLE
Cannot use OwenIt\Auditing\Contracts\Auditable as Auditable because the name is already in use

### ISSUE THREAD

**Issue by JaimeVirrueta** [owen-it/laravel-auditing-doc#60]
Hello, when i try use the package and use in a specific model i get this error

![image](https://user-images.githubusercontent.com/19581319/38290018-cda49d1c-379e-11e8-8c54-db17283468f6.png)

Please help me and thanks a lot

**Comment by quetzyg** [comment]
Hi @JaimeVirrueta,

This is not the appropriate issue tracker for this. Also, this has already been discussed several times in the past:
https://github.com/owen-it/laravel-auditing/issues/400
https://github.com/owen-it/laravel-auditing/issues/371
https://github.com/owen-it/laravel-auditing/issues/354
