### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by crashkonijn** [owen-it/laravel-auditing-doc#66]
Hi there!

I've been looking for a way to create documentation similar to yours and I've been trying to search for a package which can do this but I've been unable to find a good one.

My question is, did you make the documentation yourself or are you indeed using something to generate it?

Thanks in advance!

**Comment by quetzyg** [comment]
The documentation (as you can see from this repo) are just a bunch of markdown files with links to each other.
You can check the actual layout/webpage [here](https://github.com/owen-it/laravel-auditing.com).

Feel free to steal it.

@anteriovieira is probably a better person to answer more technical questions about that last repo, than I am.

**Comment by anteriovieira** [comment]
Hi @crashkonijn 

The documentation is stored in the [owen-it/laravel-auditing-doc](https://github.com/owen-it/laravel-auditing-doc) repository in markdown format as the @quetzyg  mentioned.

> My question is, did you make the documentation yourself or are you indeed using something to generate it?

Our application is just a clone of the reposiorio [laravel/laravel.com](https://github.com/laravel/laravel.com) with some modifications. We do not use third party packages to generate the site, we just read the markdown and [transform](https://github.com/owen-it/laravel-auditing.com/blob/v2.0/app/Services/Documentation.php#L67) it into html. You can also make the clone of the repository [owen-it/laravel-auditing.com](https://github.com/owen-it/laravel-auditing.com) and make your modifications.

The only thing I did was point the directory to the repository, so when we update the documentation it automatically reflects on the site.

```php
     // laravel-auditing.com/app/helpers.php
     function base_raw_path($path = '') 
     { 
         return env('RAW_FILE_URL') . $path; 
     } 
```

`RAW_FILE_URL = https://github.com/owen-it/laravel-auditing-doc`

Now if you want to use proper tools for building documentation I would recommend the following:

- [vuepress](https://vuepress.vuejs.org)
- [Hexo](https://hexo.io/pt-br/)
- [mkdocs](https://mkdocs.org)

**Comment by crashkonijn** [comment]
Hi guys,

Thanks for answering my question, that will definitely help!
